module.exports = {
  WordsToSymbols: {
    "argentina": "ARS",
    "argentine": "ARS",
    "argentinian": "ARS",
    "argentina peso": "ARS",
    "argentina pesos": "ARS",
    "argentine peso": "ARS",
    "argentine pesos": "ARS",
    "argentinian peso": "ARS",
    "argentinian pesos": "ARS",
    "ars": "ARS",

    "australia": "AUD",
    "australian": "AUD",
    "australian dollar": "AUD",
    "australian dollars": "AUD",
    "aussie dollar": "AUD",
    "aussie dollars": "AUD",
    "aud": "AUD",

    "bitcoin": "BTC",
    "bitcoins": "BTC",
    "btc": "BTC",

    "brazil": "BRL",
    "brazilian": "BRL",
    "brazil real": "BRL",
    "brazil reals": "BRL",
    "brazil reais": "BRL",
    "brazilian real": "BRL",
    "brazilian reals": "BRL",
    "brazilian reais": "BRL",
    "brl":"BRL",

    "canada": "CAD",
    "canadian": "CAD",
    "canadian dollar": "CAD",
    "canadian dollars": "CAD",
    "cad":"CAD",

    "chile": "CLP",
    "chilean": "CLP",
    "chile peso": "CLP",
    "chile pesos": "CLP",
    "chilean peso": "CLP",
    "chilean pesos": "CLP",
    "clp":"CLP",

    "china": "CNY",
    "chinese": "CNY",
    "chinese renminbi": "CNY",
    "chinese yuan": "CNY",
    "yuan": "CNY",
    "cny": "CNY",

    "czech republic": "CZK",
    "czech": "CZK",
    "czech republic koruna": "CZK",
    "czech koruna": "CZK",
    "czk": "CZK",

    "denmark": "DKK",
    "danish": "DKK",
    "denmark krone": "DKK",
    "danish krone": "DKK",
    "dkk": "DKK",

    "euro": "EUR",
    "euros": "EUR",
    "EUR": "EUR",

    "fiji": "FJD",
    "fijian": "FJD",
    "fiji dollar": "FJD",
    "fiji dollars": "FJD",
    "fijian dollar": "FJD",
    "fijian dollars": "FJD",
    "fjd": "FJD",

    "honduras": "HNL",
    "honduran": "HNL",
    "catracho": "HNL",
    "honduras lempira": "HNL",
    "honduran lempira": "HNL",
    "catracho lempira": "HNL",
    "hnl": "HNL",

    "hong kong dollar": "HKD",
    "hong kong dollars": "HKD",
    "hk dollar": "HKD",
    "hk dollars": "HKD",
    "hkd": "HKD",

    "hungary": "HUF",
    "hungarian": "HUF",
    "hungary forint": "HUF",
    "hungarian forint": "HUF",
    "huf": "HUF",

    "iceland": "ISK",
    "iceland krona": "ISK",
    "isk": "ISK",

    "india rupee": "INR",
    "indian rupee": "INR",
    "inr": "INR",

    "indonesia rupiah": "IDR",
    "indonesian rupiah": "IDR",
    "idr": "IDR",

    "israel shekel": "ILS",
    "israelian shekel": "ILS",
    "ils": "ILS",

    "japan": "JPY",
    "japanese": "JPY",
    "japanese yen": "JPY",
    "jpy": "JPY",

    "korea": "KRW",
    "korean won": "KRW",
    "south korean won": "KRW",
    "krw": "KRW",

    "malaysia": "MYR",
    "malaysian ringit": "MYR",
    "myr": "MYR",

    "mexico": "MXN",
    "mexico peso": "MXN",
    "mexico pesos": "MXN",
    "mexican peso": "MXN",
    "mexican pesos": "MXN",
    "mxn": "MXN",

    "new zealand dollar": "NZD",
    "new zealand dollars": "NZD",
    "kiwi dollar":"NZD",
    "kiwi dollars":"NZD",
    "nzd": "NZD",

    "norway": "NOK",
    "norwegian": "NOK",
    "norway krone": "NOK",
    "norwegian krone": "NOK",
    "nok": "NOK",

    "pakistan": "PKR",
    "pakistan rupee": "PKR",
    "pakistan rupees": "PKR",
    "pkr": "PKR",

    "philippines": "PHP",
    "filipino peso": "PHP",
    "filipino pesos": "PHP",
    "php": "PHP",

    "poland zloty":"PLN",
    "polish zloty":"PLN",
    "pln": "PLN",

    "russia": "RUB",
    "russian ruble": "RUB",
    "rub": "RUB",

    "singapore dollar": "SGD",
    "singapore dollars": "SGD",
    "singaporean dollar": "SGD",
    "singaporean dollars": "SGD",
    "sgd": "SGD",

    "south africa": "ZAR",
    "south african rand": "ZAR",
    "zar": "ZAR",

    "sweden": "SEK",
    "swedish krona": "SEK",
    "sek": "SEK",

    "switzerland": "CHF",
    "swiss franc": "CHF",
    "chf": "CHF",

    "taiwan dollar": "TWD",
    "taiwan dollars": "TWD",
    "taiwanese dollar": "TWD",
    "taiwanese dollars": "TWD",
    "twd": "TWD",

    "thailand": "THB",
    "thailand baht": "THB",
    "thai baht": "THB",
    "thb": "THB",

    "turkey": "TRY",
    "turkey lira": "TRY",
    "turkish lira": "TRY",
    "turk lira": "TRY",
    "try": "TRY",

    "united kingdom pound": "GBP",
    "great britain pound": "GBP",
    "english": "GBP",
    "english pound": "GBP",
    "english pounds": "GBP",
    "british": "GBP",
    "british pound": "GBP",
    "british pounds": "GBP",
    "gbp": "GBP",

    "united states dollar": "USD",
    "united states dollars": "USD",
    "american": "USD",
    "american dollar": "USD",
    "american dollars": "USD",
    "u.s. dollar": "USD",
    "u.s. dollars": "USD",
    "us dollar": "USD",
    "us dollars": "USD",
    "usd": "USD",

    "vietnam": "VND",
    "vietnam dong": "VND",
    "vietnamese dong": "VND",
    "vnd": "VND"
  },

  SymbolsToWords:{
    "ARS": ["Argentinian peso","Argentinian pesos"],
    "AUD": ["Australian dollar","Australian dollars"],
    "BTC": ["Bitcoin","Bitcoin"],
    "BRL": ["Brazilian Reais","Brazilian Reais"],
    "CAD": ["Canadian Dollar","Canadian Dollars"],
    "CLP": ["Chilean Peso","Chilean Pesos"],
    "CNY": ["Chinese Yuan","Chinese Yuan"],
    "CZK": ["Czech Republic Koruna","Czech Republic Koruna"],
    "DKK": ["Danish Krone","Danish Krone"],
    "EUR": ["Euro","Euros"],
    "FJD": ["Fijian Dollar","Fijian Dollars"],
    "HNL": ["Honduran Lempira","Honduran Lempira"],
    "HKD": ["Hong Kong Dollar","Hong Kong Dollars"],
    "HUF": ["Hungarian Forint","Hungarian Forint"],
    "ISK": ["Icelandic Krona","Icelandic Krona"],
    "INR": ["Indian Rupee","Indian Rupees"],
    "IDR": ["Indonesian Rupiah","Indonesian Rupiah"],
    "ILS": ["Israelian Shekel","Israelian Shekel"],
    "JPY": ["Japanese Yen","Japanese Yen"],
    "KRW": ["South Korean Won","South Korean Won"],
    "MYR": ["Malaysian Ringit","Malaysian Ringit"],
    "MXN": ["Mexican Peso","Mexican Pesos"],
    "NZD": ["New Zealand Dollar","New Zealand Dollars"],
    "NOK": ["Norwegian Krone","Norwegian Krone"],
    "PKR": ["Pakistan Rupee","Pakistan Rupees"],
    "PHP": ["Filipino Peso","Filipino Pesos"],
    "PLN": ["Polish Zloty","Polish Zloty"],
    "RUB": ["Russian Ruble","Russian Ruble"],
    "SGD": ["Singaporean Dollar","Singaporean Dollars"],
    "ZAR": ["South African Rand","South African Rand"],
    "SEK": ["Swedish Krona","Swedish Krona"],
    "CHF": ["Swiss Franc","Swiss Francs"],
    "TWD": ["Taiwanese Dollar","Taiwanese Dollars"],
    "THB": ["Thai Baht","Thai Baht"],
    "TRY": ["Turkish Lira","Turkish Lira"],
    "GBP": ["English Pound","English Pounds"],
    "USD": ["U.S. Dollar","U.S. Dollars"],
    "VND": ["Vietnam Dong","Vietnam Dong"]
  }

};
